theme = "psai-hugo-tailwind"
languageCode = "en-us"
baseurl = "http://example.com/"
title = "Szegedi Petőfi Sándor Általános Iskola és Bálint Sándor Tagiskola"

author = "Dirk Olbrich"
copyright = "Copyright © 2019-2024, Dirk Olbrich, all rights reserved."

[params]
    name = "Hugo Tailwindcss Starter"
    description = "A simple bootstraped theme for Hugo, build with Tailwindcss."

    github_user = "dirkolbrich"
    github_repo = "https://github.com/dirkolbrich/hugo-tailwindcss-starter-theme"
    github_banner = true

    favicon = "favicon.ico"

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
